package com.sdm.view.frmrelatorio;

import com.sdm.cliente.RMICliente;
import com.sdm.model.Categoria;
import com.sdm.model.Produto;
import com.sdm.server.RemoteRelatorio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class FrmRelatorio extends javax.swing.JFrame {
    
    private void setTabelaListaPrecos() {
        TabelaRelatorio.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[] {"ID", "Nome", "Preço", "Unidade", "Categoria"}
        ));
    }

    private void setTabelaAbaixoAcima() {
        TabelaRelatorio.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[] {"ID", "Nome", "Estoque Atual", "Estoque Min/Max", "Categoria"}
        ));
    }

    private void setTabelaBalanco() {
        TabelaRelatorio.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[] {"Produto", "Qtd Estoque", "Preço Unitário", "Valor Total"}
        ));
    }

    private void preencherTabelaBalanco(List<Produto> lista) {
     DefaultTableModel modelo = (DefaultTableModel) TabelaRelatorio.getModel();
        modelo.setRowCount(0);

        for (Produto p : lista) {
            double total = p.getQuantidadeEstoque() * p.getPrecoUnitario();

            modelo.addRow(new Object[]{
               p.getNome(),
                p.getQuantidadeEstoque(),
                p.getPrecoUnitario(),
                total
            });
        }

    }  

    private void preencherTabelaPorCategoria(List<Categoria> lista) {
        DefaultTableModel modelo = (DefaultTableModel) TabelaRelatorio.getModel();
        modelo.setRowCount(0);

        for (Categoria c : lista) {
            modelo.addRow(new Object[]{
                c.getNome(),
                c.getTotalProdutos()
            });
        }
    }

    private void preencherTabelaProdutos(List<Produto> lista) {
        DefaultTableModel modelo = (DefaultTableModel) TabelaRelatorio.getModel();
        modelo.setRowCount(0);

        for (Produto p : lista) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPrecoUnitario(),
                p.getUnidade(),
                p.getCategoria().getNome()
            });
        }
    }

    private void setTabelaPorCategoria() {
        TabelaRelatorio.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[] {"Categoria", "Quantidade de Produtos"}
        ));
    }

    public FrmRelatorio() {
        initComponents();
    }
    
    private void gerarRelatorio() {
        try {
            RemoteRelatorio relService = RMICliente.getRelatorioService();
            String opcao = JCSeletor.getSelectedItem().toString();

            switch (opcao) {

                case "Produtos abaixo da quantidade minima":
                    setTabelaAbaixoAcima();
                    preencherTabelaProdutos(relService.produtosAbaixoMinimo());
                    break;

                case "Produto acima da quantidade maxima":
                    setTabelaAbaixoAcima();
                    preencherTabelaProdutos(relService.produtosAcimaMaximo());
                    break;

                case "Balanço Físico e Financeiro dos produtos":
                    setTabelaBalanco();
                    preencherTabelaBalanco(relService.relatorioBalanco());
                    break;

                case "Lista de Preços dos produtos":
                    setTabelaListaPrecos();
                    preencherTabelaProdutos(relService.listarPrecos());
                    break;

                case "Relação de produtos por categoria":
                    setTabelaPorCategoria();
                    preencherTabelaPorCategoria(relService.produtosPorCategoria());
                    break;

                default:
                    JOptionPane.showMessageDialog(this, "Relatório não implementado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erro ao gerar relatório: " + e.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JCSeletor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaRelatorio = new javax.swing.JTable();
        JBGerarRelatótios = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        JCSeletor.setBackground(new java.awt.Color(0, 0, 0));
        JCSeletor.setForeground(new java.awt.Color(204, 204, 255));
        JCSeletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de Preços dos produtos", "Balanço Físico e Financeiro dos produtos", "Produtos abaixo da quantidade minima", "Produto acima da quantidade maxima", "Relação de produtos por categoria" }));
        JCSeletor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCSeletorActionPerformed(evt);
            }
        });

        TabelaRelatorio.setBackground(new java.awt.Color(0, 0, 0));
        TabelaRelatorio.setForeground(new java.awt.Color(204, 204, 255));
        TabelaRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Unidade de medida", "Categoria"
            }
        ));
        TabelaRelatorio.setSelectionForeground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(TabelaRelatorio);

        JBGerarRelatótios.setBackground(new java.awt.Color(0, 0, 0));
        JBGerarRelatótios.setFont(new java.awt.Font("Source Serif Pro", 1, 18)); // NOI18N
        JBGerarRelatótios.setForeground(new java.awt.Color(204, 204, 255));
        JBGerarRelatótios.setText("Gerar Relatório");
        JBGerarRelatótios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.white, null));
        JBGerarRelatótios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGerarRelatótiosActionPerformed(evt);
            }
        });

        JBVoltar.setBackground(new java.awt.Color(0, 0, 0));
        JBVoltar.setFont(new java.awt.Font("Source Serif Pro", 1, 18)); // NOI18N
        JBVoltar.setForeground(new java.awt.Color(204, 204, 255));
        JBVoltar.setText("Voltar");
        JBVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, java.awt.Color.white, null));
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Source Serif Pro Black", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Relatórios de Estoque");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(886, 886, 886)
                        .addComponent(JBGerarRelatótios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JCSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170)
                                .addComponent(JBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(JBVoltar)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JCSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addComponent(JBGerarRelatótios)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCSeletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCSeletorActionPerformed
        gerarRelatorio(); // ← Atualiza a tabela automaticamente
    }//GEN-LAST:event_JCSeletorActionPerformed

    private void JBGerarRelatótiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGerarRelatótiosActionPerformed
        // TODO add your handling code here:
        try {
        RemoteRelatorio relService = RMICliente.getRelatorioService();
        String opcao = JCSeletor.getSelectedItem().toString();

        switch (opcao) {

            // ✔ PRODUTOS ABAIXO DO MÍNIMO
            case "Produtos abaixo da quantidade minima":
                setTabelaAbaixoAcima();
                preencherTabelaProdutos(relService.produtosAbaixoMinimo());
                break;

            // ✔ PRODUTOS ACIMA DO MÁXIMO
            case "Produto acima da quantidade maxima":
                setTabelaAbaixoAcima();
                preencherTabelaProdutos(relService.produtosAcimaMaximo());
                break;

            // ✔ BALANÇO FÍSICO/FINANCEIRO
            case "Balanço Físico e Financeiro dos produtos":
                setTabelaBalanco();
                preencherTabelaBalanco(relService.relatorioBalanco());
                break;

            // ✔ LISTA DE PREÇOS
            case "Lista de Preços dos produtos":
                setTabelaListaPrecos();
                preencherTabelaProdutos(relService.listarPrecos());
                break;

            // ✔ RELAÇÃO PRODUTOS POR CATEGORIA
            case "Relação de produtos por categoria":
                setTabelaPorCategoria();
                preencherTabelaPorCategoria(relService.produtosPorCategoria());
                break;

            default:
                JOptionPane.showMessageDialog(this, "Relatório não implementado.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Erro ao gerar relatório: " + e.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);

        e.printStackTrace();
    }
       
    }//GEN-LAST:event_JBGerarRelatótiosActionPerformed

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JBVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGerarRelatótios;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JComboBox<String> JCSeletor;
    private javax.swing.JTable TabelaRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
