/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sdm.view.frmproduto;

import com.sdm.model.Categoria;
import com.sdm.model.Produto;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Master
 */
public class FrmEditarProduto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEditarProduto.class.getName());

    /**
     * Creates new form FrmEditarProduto
     */
    // Variáveis para armazenar o produto selecionado e o ID da Categoria
    private Produto produtoSelecionado;
    private int idCategoriaSelecionada;
    private List<Categoria> listaCategorias; // Para manter a lista de categorias carregadas

    
    // Método para carregar a lista de categorias e popular o ComboBox (necessário para o UPDATE)
    private void carregarCategorias() {
        try {
            // Supondo que você tem um método listarCategorias no ServiceFacade
            
            JCBUnidade.removeAllItems(); // Remove "Selecionar", "Kg", "g", etc.
            
            // Adiciona as unidades fixas (ou crie um ComboBox separado para as Categorias)
            JCBUnidade.addItem("Kg");
            JCBUnidade.addItem("g");
            JCBUnidade.addItem("L");
            JCBUnidade.addItem("ml");
            
            // Se você tiver um ComboBox para Categoria, implemente a lógica aqui
            // Ex: JCBCategoria.addItem(c.getNome()); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar categorias: " + e.getMessage(), "Erro de Categoria", JOptionPane.ERROR_MESSAGE);
            logger.severe("Erro ao carregar categorias: " + e.getMessage());
        }
    }

    // Método para popular a JTable com os dados dos Produtos
    private void carregarTabelaProdutos() {
       
    }
    
    // Adiciona o Listener para o clique na tabela
    private void adicionarListenerTabela() {
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int linha = jTable1.getSelectedRow();
                if (linha != -1) {
                    preencherCampos(linha);
                }
            }
        });
    }

    // Preenche os campos de texto com os dados da linha selecionada
    private void preencherCampos(int linha) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        try {
            int idProduto = (Integer) modelo.getValueAt(linha, 0);
            
            // Busca o produto completo para ter acesso ao objeto Categoria
           
            
            if (produtoSelecionado != null) {
                JTFNome.setText(produtoSelecionado.getNome());
                // Formate o preço e o peso para exibição se necessário (ex: Locale)
                JTFPreco.setText(String.valueOf(produtoSelecionado.getPrecoUnitario()));
                JTFPeso.setText(String.valueOf(produtoSelecionado.getPeso())); // <<< ASSUMIMOS ESTE CAMPO
                JTFAtual.setText(String.valueOf(produtoSelecionado.getQuantidadeEstoque()));
                JTFMinima.setText(String.valueOf(produtoSelecionado.getQuantidadeMinima()));
                JTFMáxima.setText(String.valueOf(produtoSelecionado.getQuantidadeMaxima()));

                // Seleciona a unidade correta no ComboBox
                JCBUnidade.setSelectedItem(produtoSelecionado.getUnidade());
                
                // Armazena o ID da categoria original para o UPDATE
                if (produtoSelecionado.getCategoria() != null) {
                    idCategoriaSelecionada = produtoSelecionado.getCategoria().getId();
                }

                JBAlterar.setEnabled(true);
                JBApagar.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar produto: " + e.getMessage(), "Erro de RMI", JOptionPane.ERROR_MESSAGE);
            logger.severe("Erro ao buscar produto: " + e.getMessage());
        }}
    public FrmEditarProduto() {
        initComponents();
        carregarCategorias(); // Carrega as categorias no ComboBox
        carregarTabelaProdutos(); // Popula a tabela
        adicionarListenerTabela(); // Adiciona o evento de clique na tabela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTFPeso = new javax.swing.JTextField();
        JCBUnidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        JTFAtual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTFMinima = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTFMáxima = new javax.swing.JTextField();
        JBSair = new javax.swing.JButton();
        JBApagar = new javax.swing.JButton();
        JBAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Preço por unidade", "Peso da unidade", "Tipo da unidade", "Quantidade atual", "Quantidade  mínima", "Quantidade máxima", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        jLabel1.setText("Nome:");

        JTFNome.setBackground(new java.awt.Color(0, 0, 0));
        JTFNome.setForeground(new java.awt.Color(204, 204, 255));
        JTFNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        JTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        jLabel2.setText("Preço por unidade:");

        JTFPreco.setBackground(new java.awt.Color(0, 0, 0));
        JTFPreco.setForeground(new java.awt.Color(204, 204, 255));
        JTFPreco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel3.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        jLabel3.setText("Peso da unidade:");

        jLabel4.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        jLabel4.setText("Tipo da unidade:");

        JTFPeso.setBackground(new java.awt.Color(0, 0, 0));
        JTFPeso.setForeground(new java.awt.Color(204, 204, 255));
        JTFPeso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        JCBUnidade.setBackground(new java.awt.Color(0, 0, 0));
        JCBUnidade.setFont(new java.awt.Font("Source Serif Pro", 1, 12)); // NOI18N
        JCBUnidade.setForeground(new java.awt.Color(204, 204, 255));
        JCBUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Kg", "g", "L", "ml" }));
        JCBUnidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel5.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        jLabel5.setText("Quantidade atual em estoque:");

        JTFAtual.setBackground(new java.awt.Color(0, 0, 0));
        JTFAtual.setForeground(new java.awt.Color(204, 204, 255));
        JTFAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel6.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        jLabel6.setText("Quantidade mínima em estoque:");

        JTFMinima.setBackground(new java.awt.Color(0, 0, 0));
        JTFMinima.setForeground(new java.awt.Color(204, 204, 255));
        JTFMinima.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel7.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        jLabel7.setText("Quantidade máxima em estoque: ");

        JTFMáxima.setBackground(new java.awt.Color(0, 0, 0));
        JTFMáxima.setForeground(new java.awt.Color(204, 204, 255));
        JTFMáxima.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        JTFMáxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFMáximaActionPerformed(evt);
            }
        });

        JBSair.setBackground(new java.awt.Color(0, 0, 0));
        JBSair.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        JBSair.setForeground(new java.awt.Color(204, 204, 255));
        JBSair.setText("Sair");
        JBSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });

        JBApagar.setBackground(new java.awt.Color(0, 0, 0));
        JBApagar.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        JBApagar.setForeground(new java.awt.Color(204, 204, 255));
        JBApagar.setText("Apagar");
        JBApagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        JBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagarActionPerformed(evt);
            }
        });

        JBAlterar.setBackground(new java.awt.Color(0, 0, 0));
        JBAlterar.setFont(new java.awt.Font("Source Serif Pro", 1, 15)); // NOI18N
        JBAlterar.setForeground(new java.awt.Color(204, 204, 255));
        JBAlterar.setText("Alterar");
        JBAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JTFPreco)
                    .addComponent(JTFPeso))
                .addGap(172, 172, 172)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(JTFMáxima, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(JBApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(JBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFMáxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(JTFAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 125, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBApagar)
                            .addComponent(JBSair)
                            .addComponent(JBAlterar))
                        .addGap(23, 23, 23))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFMáximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFMáximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFMáximaActionPerformed

    private void JTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeActionPerformed

    private void JBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBApagarActionPerformed

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_JBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEditarProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBApagar;
    private javax.swing.JButton JBSair;
    private javax.swing.JComboBox<String> JCBUnidade;
    private javax.swing.JTextField JTFAtual;
    private javax.swing.JTextField JTFMinima;
    private javax.swing.JTextField JTFMáxima;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JTextField JTFPeso;
    private javax.swing.JTextField JTFPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
